# backend/netlify/netlify.toml
[build]
  # Base directory for builds (relative to repository root)
  base = ""

  # Default build command (override per-branch if needed)
  command = "echo 'Netlify build triggered' && exit 0"

  # Directory to publish (Netlify will auto-detect if omitted)
  publish = ""

  # Environment variables available during build
  [build.environment]
    NODE_VERSION = "16"
    REPOSITORY_URL = "https://github.com/Aswanthrajan/blue"

# Branch-specific build settings
[context.production]  # Used when deploying main branch
  command = "echo 'Production build (main branch)'"

[context.branch-deploy]  # Applies to all branch deploys
  command = "echo 'Branch deployment detected'"

# Blue environment settings (priority over branch-deploy)
[context.blue]
  command = "npm run build:blue"
  environment = { 
    ENV_TYPE = "blue",
    DEPLOYMENT_GROUP = "production"
  }

# Green environment settings (priority over branch-deploy)
[context.green]
  command = "npm run build:green"
  environment = { 
    ENV_TYPE = "green",
    DEPLOYMENT_GROUP = "staging"
  }

# Edge functions configuration
[[edge_functions]]
  path = "/*"
  function = "route"

# Redirects configuration (will be overridden by _redirects file)
[[redirects]]
  from = "/*"
  to = "/blue/:splat"
  status = 200
  force = false

# Branch-specific headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Deployment-Type = "blue-green"
    Cache-Control = "no-cache"

  # Blue environment headers
  [headers.values.blue]
    X-Environment = "blue"
    X-Status = "active"

  # Green environment headers
  [headers.values.green]
    X-Environment = "green"
    X-Status = "inactive"

# Build plugins (optional)
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    exclude = ["/admin/*"]

# Monitoring settings
[monitoring]
  enabled = true